apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-configmap
data:
  producer-topic: topic-01
  producer-client-id: test-producer-client
  producer-bootstrap-servers:  localhost:9092, localhost:9093, localhost:9094
